# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters

use_gravity_comp    : 1

Kp_abad             : 40
Kd_abad             : 5

Kp_femur            : 40
Kd_femur            : 5

Kp_tibia            : 40
Kd_tibia            : 5

lon_gain            : .05
lat_gain            : .02
vert_gain           : .06
pitch_gain          : .05
roll_gain           : .02
yaw_gain            : .06

# # Desired state commands - maybe add these back in later
# des_p             : [0,0,0.26]
# des_theta         : [0,0,0]
# des_dp            : [0,0,0]
# des_dtheta        : [0,0,0]
# des_theta_max     : [0,0.4,0]
# des_dp_max        : [1.0,0.5,0]
# des_dtheta_max    : [0,0,3]
