# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters

use_gravity_comp    : 1

Kp_abad             : 40
Kd_abad             : 5

Kp_femur            : 40
Kd_femur            : 5

Kp_tibia            : 40
Kd_tibia            : 5

lon_gain            : .000025
lat_gain            : .000025
vert_gain           : .000025
pitch_gain          : .0005
roll_gain           : .0002
yaw_gain            : .0006
home_max_dq         : .0002

# # Desired state commands - maybe add these back in later
# des_p             : [0,0,0.26]
# des_theta         : [0,0,0]
# des_dp            : [0,0,0]
# des_dtheta        : [0,0,0]
# des_theta_max     : [0,0.4,0]
# des_dp_max        : [1.0,0.5,0]
# des_dtheta_max    : [0,0,3]
